<?php
$styleSlide= $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/swiper.min.css')?>" />
<style type="text/css">
	.swiper-pagination-bullet {
	  background: #fff;
	  opacity: 0.5;
	}

	.swiper-pagination-bullet-active {
	  background: #fff;
	  opacity: 1;
	}
</style>
<script type="text/javascript">
    require(['jquery','magestore/swiper'], function($, Swiper) {
        $(document).ready(function($) {
            var mySwiper = new Swiper('.swiper-container', {
                parallax: true,
	            pagination: '.swiper-pagination',
    			paginationClickable: true,
    			autoplay: 5000,
                speed: 1000,
                watchSlidesVisibility: true,
    			loop: true,
                nextButton: '.swiper-button-next',
                prevButton: '.swiper-button-prev'
			});   
        });
    });
</script>

<div class="swiper-container" style="height: 100vh">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <!-- Slides -->
		<?php foreach ($block->getBannerCollection() as $banner) : ?>
	        <div class="swiper-slide">
			        <div class="main-page-slide" style="background-image: url(<?php echo $block->getBannerImageUrl($banner); ?>); background-position: center; background-size: cover; width: 100%; height: 100%" >
			        	<div class="container">
                            <div class="banner-desc">
                                <?php echo $banner->getImageAlt() ?>
                                <a href="<?php echo $banner->getClickUrl(); ?>"
                                   target="<?php echo $banner->getTargetValue(); ?>"
                                   class="banner-link" >
                                    <span class="banner-dash"></span>Shop Now
                                </a>
                            </div>
                        </div>
			        </div>
		    </div>
		<?php endforeach ?>
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next fa fa-angle-right"></div>
    <div class="swiper-button-prev fa fa-angle-left"></div>
</div>

<div class="home slider">
</div>
