<?php /** * Copyright © 2013-2017 Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ ?>
<?php /** * Category view template * * @var $block \Magento\Catalog\Block\Category\View */ ?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_category = $block->getCurrentCategory(); $_imgHtml = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = "<div class=\"category-image\" style=\"background-image: url('" . $_imgUrl. "')\"></div>";
        echo $_imgHtml;
    }
?>