<?php
/**
 * Navbar for store
 *
 * @var $block \Binayak\ScratchMod\Block\Html\Navbar
 */
?>

<?php $_menu = $block->getHtml() ?>

<div class="navigation-overlay">
  <div class="container-fluid relative">
    <div class="row">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Logo -->
        <div class="logo-container">
          <div class="logo-wrap local-scroll">

            <?php if ($block->isHomePage()):?>
                <a class="logo" href="#" title="Aadikara" >
            <?php else: ?>
                <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="Aadikara">
            <?php endif ?>
                    <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                         alt="Aadikara"
                    />
                </a>
          </div>
        </div>
      </div> <!-- end navbar-header -->

      <div class="menu-socials hidden-sm hidden-xs">
        <ul>
          <li>
          
          </li>
          <li>
            <?php echo $block->getChildHtml('minicart'); ?>
          </li>
        </ul>
      </div>

      <div class="col-md-8 col-xs-12 nav-wrap">
        <div class="collapse navbar-collapse text-center" id="navbar-collapse">

          <ul class="nav navbar-nav local-scroll text-right">

            <?php /* @escapeNotVerified */ echo $_menu; ?>

          </ul>
        </div>
      </div> <!-- end col -->


    </div> <!-- end row -->
  </div> <!-- end container -->
</div> <!-- end navigation -->
