<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="subscribe-form-wrapper">
    <h2> Stay Updated </h2>
    <div class="content">
        <form class="subscribe-form"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">

            <input name="email"
                   type="email"
                   id="newsletter"
                   class="subscribe-form-input"
                   placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                   data-validate="{required:true, 'validate-email':true}"/>

            <button class="subscribe-form-btn" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
            </button>

        </form>
    </div>
</div>
